#!/bin/sh
if [ -z "$(bspc query -N -n .focused.fullscreen -d focused)" ]; then
	bspc node focused.tiled -t fullscreen
	polybar-msg cmd hide
else
	bspc node focused.fullscreen -t tiled
	~/.config/scripts/bspunhide
    polybar-msg cmd show
fi
