#!/bin/sh

# Shows the current moon phase.
moonfile="$HOME/.local/share/moonphase"

[ "$(stat -c %y "$moonfile" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] ||
	{ curl -sf "wttr.in/?format=%m" > "$moonfile" || exit 1 ;}

icon="$(cat "$moonfile")"

case "$icon" in
	🌑) echo "";;
	🌒) echo "" ;;
	🌓) echo "" ;;
	🌔) echo "" ;;
	🌕) echo "" ;;
	🌖) echo "" ;;
	🌗) echo "" ;;
	🌘) echo "" ;;
	*) exit 1 ;;
esac
